name: Greetings
on: 
  push:
    branches: ["main"]
jobs:
  myfirstjob:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: List all files and folders
      run: |
        ls -ltr
        echo "Testing Self hosted runner"
